import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import { AppHeader } from "@/components/app-header/AppHeader";
import { Footer } from "@/components/footer/Footer";
import "./globals.css";
import { Button } from "@/components/button/Button";
import { Discord } from "@/components/icons";

const inter = Courier_Prime({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HAMACA – Gary introduces you the first meme coin with a meaning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modals,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader>
          <div className="flex items-center flex-1 gap-6">
            <Link href="/">
              <Image
                src="/logo.jpeg"
                alt="Hamaca logo"
                width={100}
                height={100}
              />
            </Link>
            <AppHeader.Nav className="hidden md:block" />
          </div>
          <a href="https://discord.com/invite/aDXHy4D8vw" target="_blank">
            <Button variant="secondary" className="flex items-center gap-2">
              <span>Join Our Discord</span>
              <Discord />
            </Button>
          </a>
        </AppHeader>
        {children}
        {modals}
        <Footer />
      </body>
    </html>
  );
}
